### ISSUE TITLE
after import project

### ISSUE THREAD

**Issue by LucsonDeveloper** [adjust/corona_sdk#11]
Caused by: groovy.lang.GroovyRuntimeException: Ambiguous method overloading for method java.io.File#<init>.
Cannot resolve which method to invoke for [null] due to overlapping prototypes between:
	[class java.lang.String]
	[class java.net.URI]
in android after import project .

**Comment by uerceg** [comment]
@LucsonDeveloper I don't see how this issue relates to our SDK nor was I able to reproduce it. Is it still the issue for you or did you manage to solve it?

**Comment by uerceg** [comment]
@LucsonDeveloper Any update on this one?

**Comment by uerceg** [comment]
In case issue is still there, feel free to reopen it. Cheers.
