### ISSUE TITLE
Add plugin to Solar2D free plugin directory

### ISSUE THREAD

**Issue by Shchvova** [adjust/corona_sdk#21]
Hello!
I'm Vlad, developer currently running Solar2D (ex Corona SDK). I made a free plugin directory. If you would Allow me, I would add this plugin to the directory, I can also make a pull request and access to add some kind of automation of one button script to deploy plugin updates to the free plugin directory.
Policy is that I am always asking for permission of plugin developers to add their plugins there. Please, reply

**Comment by uerceg** [comment]
Hi Vlad,

Long time no type, hope everything's running well on your end with Solar2D.

Feel free to, sounds interesting. Is there anything from legal perspective which Adjust as company needs to commit to in this kind of a deal?

**Comment by Shchvova** [comment]
No, nothing. License allows me to do it without any legality. I will set it up and give you (@uerceg) access when it is ready.

**Comment by uerceg** [comment]
Sounds great, thanks!

**Comment by Shchvova** [comment]
This is fixed by #22

**Comment by uerceg** [comment]
👋 @Shchvova

Hope you're doing well. Reopening this one because I'm noticing that [`deployToDirectory.sh`](https://github.com/adjust/corona_sdk/blob/master/plugin/deployToDirectory.sh) script is now failing once being executed. Fails with this error:

```
rm: /Users/uerceg/GitHub/corona_sdk_dev/plugin/ios/BuiltPlugin: No such file or directory
```

Do you have an idea for some quick fix?

Cheers!

**Comment by uerceg** [comment]
Closed with https://github.com/adjust/corona_sdk/pull/33. Thank you!
