### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by AleCGames** [adjust/corona_sdk#25]
Hi,
I'm trying to make a build with the Adjust plugin added to my project but the build fails.
I have added the following line to my 'build.settings' file:

["plugin.adjust"] =
{
    publisherId = "com.adjust"
},

**The result from the console:**

FAILURE: Build failed with an exception.
03:00:49.443
03:00:49.443 * What went wrong:
03:00:49.443 Could not determine the dependencies of task ‘:App:lintVitalRelease’.
03:00:49.443 > Could not resolve all artifacts for configuration ‘:App:debugCompileClasspath’.
03:00:49.443 > Could not find play-services-ads-identifier-17.0.0.jar (com.google.android.gms:play-services-ads-identifier:17.0.0).
03:00:49.443 Searched in the following locations:
03:00:49.443 https://dl.google.com/dl/android/maven2/com/google/android/gms/play-services-ads-identifier/17.0.0/play-services-ads-identifier-17.0.0.jar
03:00:49.443
03:00:49.443 * Try:
03:00:49.443 Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
03:00:49.443
03:00:49.443 * Get more help at https://help.gradle.org
03:00:49.443

**Comment by uerceg** [comment]
Hi @AleCGames 

I am not sure this should be related to our SDK. Error pretty much says that Gradle was unable to pull `play-services-ads-identifier-17.0.0.jar` from Maven. Our SDK is not adding this dependency to your app by default. In our README we are having this step described as something users should add on their own. So I guess question is if you're having this line in Gradle settings file added somewhere in your app?

**Comment by AleCGames** [comment]
Hi @uerceg 

Thank you for your answer.

I just tried to compile now and the issue persists. So by removing the code that adds the _Adjust_ plugin to my project in the **build.settings** file the build was done.

The code I removed from build.settings file:

```
["plugin.adjust"] =
{
       publisherId = "com.adjust"
},

```

Besides, my project does not have a Gradle setting because I make my games 100% Lua code, i don't use native code. I make my projects in Corona(Solar2D) simulator, not Android Studio.

**Comment by AleCGames** [comment]
> Hi @AleCGames
> 
> I am not sure this should be related to our SDK. Error pretty much says that Gradle was unable to pull `play-services-ads-identifier-17.0.0.jar` from Maven. Our SDK is not adding this dependency to your app by default. In our README we are having this step described as something users should add on their own. So I guess question is if you're having this line in Gradle settings file added somewhere in your app?

Hi @uerceg 
Read my recent comment about it.

**Comment by uerceg** [comment]
Hi @AleCGames 

Can you give our latest SDK version a shot and let us know if you're still facing this issue?

**Comment by AleCGames** [comment]
> Hi @AleCGames
> 
> Can you give our latest SDK version a shot and let us know if you're still facing this issue?

Hi @uerceg 

I've tested it an it works now. Thank you!

**Comment by uerceg** [comment]
Great news, thanks for checking. Any reason for reopening the issue or can it be closed?
