### ISSUE TITLE
RuntimeTaskDispatcher, it should be checked for null before sending.

### ISSUE THREAD

**Issue by bulupe** [adjust/corona_sdk#6]
https://github.com/adjust/corona_sdk/blob/0d735e355b54f73d32c8d22a21307da03ce43df0/plugin/android/plugin/src/main/java/plugin/adjust/LuaLoader.java#L236

This causes a crash on Android devices, it can happen if CoronaRuntime is busy at this moment and plugin sends one more event that brakes all the execution.

Here is the error example;

> com.naef.jnlua.LuaState.lua_newtable (Unknown Source)
> com.naef.jnlua.LuaState.newTable (Unknown Source)
> com.ansca.corona.CoronaLua.newEvent (CoronaLua.java:99)
> plugin.adjust.LuaLoader$1.executeUsing (LuaLoader.java:235)
> com.ansca.corona.CoronaRuntimeTaskDispatcher$TaskEvent.Send (CoronaRuntimeTaskDispatcher.java:170)
> com.ansca.corona.events.EventManager.sendEvents (EventManager.java:91)
> com.ansca.corona.Controller.updateRuntimeState (Controller.java:308)
> com.ansca.corona.graphics.opengl.CoronaGLSurfaceView$CoronaRenderer.onDrawFrame (CoronaGLSurfaceView.java:425)
> com.ansca.corona.graphics.opengl.GLSurfaceView$GLThread.guardedRun (GLSurfaceView.java:1623)
> com.ansca.corona.graphics.opengl.GLSurfaceView$GLThread.run (GLSurfaceView.java:1378)

<img width="645" alt="screen shot 2018-05-18 at 00 01 39" src="https://user-images.githubusercontent.com/1403063/40204144-28e4b9d8-5a30-11e8-85df-47b512e3b1f1.png">

**Comment by uerceg** [comment]
@bulupe 

Should be solved with Corona SDK 4.13.1 (https://github.com/adjust/corona_sdk/releases/tag/v4.13.1). Feel free to give it a try and in case the issue still persists, feel free to reopen this issue.

Thank you one more time for reporting.

Cheers. 🍺

**Comment by bulupe** [comment]
Cheers
